# Generated by Django 4.2.16 on 2025-07-24 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_section', '0002_designation_jobposting_jobwhyjoinus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_section.designation', verbose_name='Designation'),
        ),
    ]
