# Generated by Django 4.2.16 on 2025-12-30 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_section', '0003_jobposting_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='education',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Education Required'),
        ),
        migrations.CreateModel(
            name='JobPostingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100, verbose_name='Skill')),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hr_section.jobposting', verbose_name='Job Posting')),
            ],
        ),
    ]
