# Generated by Django 4.2.16 on 2026-05-15 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_section', '0005_erpenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_target_based', models.BooleanField(default=False)),
                ('target_details', models.TextField(blank=True, null=True)),
                ('contract_period', models.CharField(blank=True, max_length=100, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=100, null=True)),
                ('probation_period', models.CharField(blank=True, max_length=100, null=True)),
                ('duty_type', models.CharField(choices=[('onsite', 'Onsite'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='ONSITE', max_length=20)),
                ('working_days', models.CharField(blank=True, max_length=100, null=True)),
                ('timing', models.CharField(blank=True, max_length=100, null=True)),
                ('food_accommodation', models.CharField(blank=True, default='NIL', max_length=255, null=True)),
                ('joining_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('hr_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
