# Generated by Django 6.0.6 on 2026-09-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_section', '0006_offerletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerletter',
            name='monthly_salary',
        ),
        migrations.AddField(
            model_name='offerletter',
            name='allowances',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
