# Generated by Django 4.2.16 on 2025-04-09 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='leads.lead')),
            ],
        ),
    ]
