# Generated by Django 4.2.16 on 2025-04-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='interested_in',
            new_name='enquiry',
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
