# Generated by Django 4.2.16 on 2025-07-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_company_alter_lead_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('lost', 'Lost'), ('follow_up', 'Follow Up'), ('sent', 'Sent'), ('in_progress', 'In Progress'), ('converted', 'Converted')], default='new', max_length=50),
        ),
    ]
