# Generated by Django 4.2.16 on 2025-08-08 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_alter_quotationordermodel_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0005_alter_lead_lead_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='location',
            new_name='company_location',
        ),
        migrations.AddField(
            model_name='lead',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='project_requirement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.salesperson'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='CustomUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
