# Generated by Django 4.2.16 on 2025-08-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_rename_location_lead_company_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('lost', 'Lost'), ('follow_up', 'Follow Up'), ('created', 'Created'), ('in_progress', 'In Progress'), ('converted', 'Converted')], default='new', max_length=50),
        ),
    ]
