# Generated by Django 4.2.16 on 2025-11-17 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_category_location_source_marketingreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='lead_city',
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('my_lead', 'My Lead'), ('assigned_lead', 'Assigned Lead')], default='my_lead', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.location'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='leads.source'),
        ),
    ]
