# Generated by Django 4.2.16 on 2025-11-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_lead_company_location_remove_lead_lead_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='company_address',
            new_name='address',
        ),
    ]
