# Generated by Django 4.2.16 on 2025-11-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_followup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='type',
        ),
        migrations.AddField(
            model_name='followup',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
