# Generated by Django 4.2.16 on 2025-11-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminders',
            name='type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('meeting', 'Meeting')], default='call', max_length=50),
        ),
    ]
