# Generated by Django 4.2.16 on 2025-11-24 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_rename_subject_meeting_title_meeting_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('status_change', 'Status Changed'), ('deleted', 'Deleted'), ('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('quotation', 'Quotation')], max_length=50)),
                ('action', models.CharField(max_length=255)),
                ('related_model', models.CharField(blank=True, max_length=100, null=True)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='leads.lead')),
            ],
        ),
    ]
