# Generated by Django 4.2.16 on 2026-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_category',
            field=models.CharField(choices=[('client', 'Client'), ('internal', 'Internal')], default='client', max_length=50),
        ),
    ]
