# Generated by Django 4.2.16 on 2026-02-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_lead_lead_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_category',
            field=models.CharField(choices=[('client', 'Client'), ('intern', 'Intern')], default='client', max_length=50),
        ),
    ]
