# Generated by Django 4.2.16 on 2026-03-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_lead_lead_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_contact',
            field=models.BooleanField(default=False),
        ),
    ]
