# Generated by Django 4.2.16 on 2026-03-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_lead_lead_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminders',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
