# Generated by Django 4.2.16 on 2026-04-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_communicationlog_whatsappdetail_emaildetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
