# Generated by Django 4.2.16 on 2026-05-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_lead_lead_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='other_category_detail',
            field=models.CharField(blank=True, help_text="Specify details if category is 'Other'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_category',
            field=models.CharField(choices=[('client', 'Client'), ('intern', 'Intern'), ('other', 'Other')], default='client', max_length=50),
        ),
    ]
