# Generated by Django 4.2.16 on 2026-06-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0032_alter_coursepayment_installments'),
        ('leads', '0023_lead_other_category_detail_alter_lead_lead_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='internship.course'),
        ),
    ]
