# Generated by Django 6.0.6 on 2026-09-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_lead_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='academic_status',
            field=models.CharField(blank=True, choices=[('hot', 'Hot Lead'), ('not_respond', 'Not Respond'), ('number_not_valid', 'Number Not Valid'), ('not_connected', 'Not Connected'), ('invalid', 'Invalid Lead')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='add_on_course_attended',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_starting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
