# Generated by Django 4.2.16 on 2026-10-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_lead_academic_status_lead_add_on_course_attended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('lost', 'Lost'), ('follow_up', 'Follow Up'), ('created', 'Created'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('rnr', 'Rnr'), ('prospects', 'Prospects'), ('details_shared', 'Details shared'), ('registration', 'Registration')], default='new', max_length=50),
        ),
    ]
