# Generated by Django 4.2.16 on 2026-10-08 08:45

from django.db import migrations, models


def update_lead_database_schema(apps, schema_editor):
    connection = schema_editor.connection
    table_name = "leads_lead"

    with connection.cursor() as cursor:

        # Remove academic_status only if it exists
        cursor.execute(
            f"SHOW COLUMNS FROM `{table_name}` LIKE 'academic_status'"
        )

        if cursor.fetchone():
            cursor.execute(
                f"ALTER TABLE `{table_name}` DROP COLUMN `academic_status`"
            )

        # Add priority_status only if it does not exist
        cursor.execute(
            f"SHOW COLUMNS FROM `{table_name}` LIKE 'priority_status'"
        )

        if not cursor.fetchone():
            cursor.execute(
                f"""
                ALTER TABLE `{table_name}`
                ADD COLUMN `priority_status` varchar(50) NULL
                """
            )


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_alter_lead_lead_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    update_lead_database_schema,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],

            state_operations=[
                migrations.RemoveField(
                    model_name='lead',
                    name='academic_status',
                ),

                migrations.AddField(
                    model_name='lead',
                    name='priority_status',
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ('hot', 'Hot'),
                            ('warm', 'Warm'),
                            ('cool', 'Cool'),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),

                migrations.AlterField(
                    model_name='lead',
                    name='lead_status',
                    field=models.CharField(
                        choices=[
                            ('new', 'New'),
                            ('contacted', 'Contacted'),
                            ('lost', 'Lost'),
                            ('follow_up', 'Follow Up'),
                            ('created', 'Created'),
                            ('in_progress', 'In Progress'),
                            ('converted', 'Converted'),
                            ('rnr', 'Rnr'),
                            ('number_not_valid', 'Number Not Valid'),
                            ('prospects', 'Prospects'),
                            ('details_shared', 'Details shared'),
                            ('registration', 'Registration'),
                        ],
                        default='new',
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]