# Generated by Django 4.2.16 on 2026-10-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_remove_lead_academic_status_lead_priority_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority_status',
            field=models.CharField(blank=True, choices=[('hot', 'prospects'), ('warm', 'Warm'), ('cold', 'Cold')], max_length=50, null=True),
        ),
    ]
