# Generated by Django 4.2.16 on 2025-10-04 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_from_account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_to',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_to_account',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalLine',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
