# Generated by Django 4.2.16 on 2025-10-06 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_customuser_force_logout_time'),
        ('finance', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.salesperson'),
        ),
    ]
