# Generated by Django 4.2.16 on 2025-10-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_journalentry_salesperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('journal_voucher', 'Journal Voucher')], max_length=50, null=True),
        ),
    ]
