# Generated by Django 4.2.16 on 2025-10-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_journalentry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='type_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
