# Generated by Django 4.2.16 on 2025-10-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_creditnote_debitnote_debitnoteitem_creditnoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('sales', 'Sales'), ('cost_of_sales', 'Cost of Sales'), ('revenue', 'Revenue'), ('general_expenses', 'General Expenses')], max_length=20),
        ),
    ]
