# Generated by Django 4.2.16 on 2025-10-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('operating', 'Operating'), ('investing', 'Investing'), ('financing', 'Financing')], max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('accounts', models.ManyToManyField(related_name='cashflow_categories', to='finance.account')),
            ],
            options={
                'unique_together': {('category', 'sub_category')},
            },
        ),
    ]
