# Generated by Django 4.2.16 on 2026-01-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_taxsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxsettings',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
