# Generated by Django 4.2.16 on 2026-01-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_taxsettings_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('journal_voucher', 'Journal Voucher'), ('tax_payment', 'Tax Payment')], max_length=50, null=True),
        ),
    ]
