# Generated by Django 4.2.16 on 2026-01-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_add_is_posting_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_posting',
            field=models.BooleanField(default=True),
        ),
    ]
