# Generated by Django - Seed AccountType and populate account_type_new

from django.db import migrations

def seed_account_types(apps, schema_editor):
    """Create the 7 standard account types."""
    AccountType = apps.get_model('finance', 'AccountType')
    
    account_types = [
        {'code': 'ASSET', 'name': 'Asset', 'classification': 'balance_sheet', 'normal_balance': 'debit', 'sort_order': 1},
        {'code': 'LIABILITY', 'name': 'Liability', 'classification': 'balance_sheet', 'normal_balance': 'credit', 'sort_order': 2},
        {'code': 'EQUITY', 'name': 'Equity', 'classification': 'balance_sheet', 'normal_balance': 'credit', 'sort_order': 3},
        {'code': 'SALES', 'name': 'Sales', 'classification': 'profit_and_loss', 'normal_balance': 'credit', 'sort_order': 4},
        {'code': 'COST_OF_SALES', 'name': 'Cost of Sales', 'classification': 'profit_and_loss', 'normal_balance': 'debit', 'sort_order': 5},
        {'code': 'REVENUE', 'name': 'Revenue', 'classification': 'profit_and_loss', 'normal_balance': 'credit', 'sort_order': 6},
        {'code': 'GENERAL_EXPENSES', 'name': 'General Expenses', 'classification': 'profit_and_loss', 'normal_balance': 'debit', 'sort_order': 7},
    ]
    
    for data in account_types:
        AccountType.objects.get_or_create(code=data['code'], defaults=data)


def populate_account_type_new(apps, schema_editor):
    """Migrate existing account type values from choice field to FK."""
    Account = apps.get_model('finance', 'Account')
    AccountType = apps.get_model('finance', 'AccountType')
    
    # Mapping from old choice value to new AccountType code
    type_map = {
        'asset': 'ASSET',
        'liability': 'LIABILITY',
        'equity': 'EQUITY',
        'sales': 'SALES',
        'cost_of_sales': 'COST_OF_SALES',
        'revenue': 'REVENUE',
        'general_expenses': 'GENERAL_EXPENSES',
    }
    
    for old_type, type_code in type_map.items():
        account_type = AccountType.objects.filter(code=type_code).first()
        if account_type:
            Account.objects.filter(type=old_type).update(account_type_new=account_type)


def reverse_populate(apps, schema_editor):
    """Reverse: set account_type_new back to null."""
    Account = apps.get_model('finance', 'Account')
    Account.objects.all().update(account_type_new=None)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_accounttype_and_account_updates'),
    ]

    operations = [
        migrations.RunPython(seed_account_types, migrations.RunPython.noop),
        migrations.RunPython(populate_account_type_new, reverse_populate),
    ]
