# Generated by Django 4.2.16 on 2026-01-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_seed_accounttype_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account_type_new',
            new_name='account_type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='type',
        ),
    ]
