# Generated by Django 4.2.16 on 2026-07-10 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0157_alter_modulepermission_module_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0015_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('journal_voucher', 'Journal Voucher'), ('payment_voucher', 'Payment Voucher'), ('tax_payment', 'Tax Payment')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('neft', 'NEFT'), ('rtgs', 'RTGS')], max_length=20)),
                ('pay_to', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_voucher_credits', to='finance.account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_voucher_debits', to='finance.account')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_voucher', to='finance.journalentry')),
                ('salesperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.salesperson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
