# Generated by Django 6.0.6 on 2026-07-15 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_financialyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialyear',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='financialyear',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialyear',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10),
        ),
        migrations.CreateModel(
            name='AccountOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='finance.account')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_balances', to='finance.financialyear')),
            ],
            options={
                'ordering': ['account__account_number'],
                'unique_together': {('account', 'financial_year')},
            },
        ),
    ]
