# Generated by Django 4.2.16 on 2026-01-24 07:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0005_remove_report_attachment_file_remove_report_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlink',
            name='description',
        ),
        migrations.AddField(
            model_name='reportlink',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
