# Generated by Django 4.2.16 on 2026-01-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0006_remove_reportlink_description_reportlink_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='week_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='week_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
