# Generated by Django 4.2.16 on 2026-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_alter_member_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'weekly')), fields=('project', 'submitted_by', 'week_start', 'week_end'), name='unique_weekly_report_per_user'),
        ),
    ]
