# Generated by Django 4.2.16 on 2026-01-27 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0009_report_unique_weekly_report_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_weekly_report_per_user',
        ),
    ]
