# Generated by Django 4.2.16 on 2026-01-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0011_rename_task_description_task_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
    ]
