# Generated by Django 4.2.16 on 2026-01-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0012_remove_member_email_remove_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
