# Generated by Django 4.2.16 on 2026-01-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0013_report_month_report_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
