# Generated by Django 4.2.16 on 2026-01-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0014_report_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='not_started', max_length=20, null=True),
        ),
    ]
