# Generated by Django 4.2.16 on 2026-01-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0015_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status_column',
        ),
    ]
