# Generated by Django 4.2.16 on 2026-04-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0016_remove_task_status_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='contract_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='project_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='taskboard',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskboard',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
