# Generated by Django 4.2.16 on 2026-09-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0017_clientcontract_contract_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
