# Generated by Django 4.2.16 on 2026-10-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0019_projectnote'),
        ('project_management', '0019_task_end_time_task_start_time'),
    ]

    operations = [
    ]
