# Generated by Django 5.2.6 on 2025-09-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Full name of the certificate requester', max_length=200)),
                ('start_date', models.DateField(help_text='Start date of the certificate period')),
                ('end_date', models.DateField(help_text='End date of the certificate period')),
                ('designation', models.CharField(blank=True, help_text='Designation or role of the requester', max_length=200, null=True)),
                ('email', models.EmailField(help_text='Email address of the requester', max_length=254)),
                ('proof_document', models.FileField(blank=True, help_text='Upload ID proof or supporting document', null=True, upload_to='certificate_proofs/')),
                ('category', models.CharField(choices=[('INTERNSHIP', 'Internship'), ('TRAINING', 'Training'), ('EMPLOYEE', 'Employee')], help_text='Category of the certificate', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Status of the certificate request', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the request was submitted')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Date and time the request was processed', null=True)),
            ],
            options={
                'verbose_name': 'Certificate Request',
                'verbose_name_plural': 'Certificate Requests',
            },
        ),
    ]
