# Generated by Django 5.2.6 on 2025-09-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Generated certificate PDF file', null=True, upload_to='certificates/'),
        ),
    ]
