# Generated by Django 5.2.6 on 2025-09-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_file',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='category',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Training', 'Training'), ('Employee', 'Employee')], help_text='Category of the certificate', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Issued', 'Issued')], default='Pending', help_text='Status of the certificate request', max_length=20),
        ),
    ]
