# Generated by Django 5.2.6 on 2025-09-11 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_remove_certificate_certificate_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Linked employee for internal certificates', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Indicates if the certificate is for an internal staff member'),
        ),
    ]
