# Generated by Django 4.2.16 on 2026-04-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificate_employee_certificate_is_internal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the certificate requester', max_length=200)),
                ('certificate_type', models.CharField(help_text='Type of the certificate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the certificate was created')),
            ],
        ),
    ]
