# Generated by Django 4.2.16 on 2026-05-22 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0155_alter_modulepermission_module_name'),
        ('certificates', '0005_certificatehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('Internship', 'Internship'), ('Job Training', 'Job Training'), ('Experience', 'Experience'), ('Employee', 'Employee'), ('Webinar', 'Webinar'), ('Internship College', 'Internship College')], max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('webinar_title', models.CharField(blank=True, max_length=255, null=True)),
                ('topics_covered', models.TextField(blank=True, null=True)),
                ('webinar_date', models.DateField(blank=True, null=True)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_unit', models.CharField(blank=True, choices=[('Hours', 'Hours'), ('Days', 'Days')], max_length=20, null=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('training_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_for_leaving', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='accounts.staffprofile')),
            ],
            options={
                'verbose_name': 'Certificate Record',
                'verbose_name_plural': 'Certificate Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignatoryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateSignatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='certificates.certificaterecord')),
                ('signatory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate_signatories', to='certificates.signatoryperson')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('certificate', 'order')},
            },
        ),
    ]
