# Generated by Django 5.2.14 on 2026-05-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificaterecord_signatoryperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterecord',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
