# Generated by Django 4.2.16 on 2024-11-28 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_business_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('terms', models.CharField(default='Due on Receipt', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('salesperson', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=255, null=True)),
                ('received_location', models.CharField(blank=True, max_length=255, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='quotations/')),
            ],
        ),
    ]
