# Generated by Django 4.2.16 on 2025-02-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_quotationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
    ]
