# Generated by Django 4.2.16 on 2025-02-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_quotationitem_total_price_quotationitem_cgst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='product_description',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.product'),
            preserve_default=False,
        ),
    ]
