# Generated by Django 4.2.16 on 2025-02-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_product_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit_price',
        ),
    ]
