# Generated by Django 4.2.16 on 2025-02-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_quotationitem_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('sales_order_id', models.CharField(max_length=50, unique=True)),
                ('sales_date', models.DateField()),
                ('purchase_order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('terms', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField()),
                ('delivery_location', models.CharField(blank=True, max_length=255)),
                ('delivery_address', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.salesperson')),
            ],
        ),
        migrations.DeleteModel(
            name='SalesOrderNew',
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.salesordermodel'),
        ),
    ]
