# Generated by Django 4.2.16 on 2025-02-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_salesorderitem_salesordermodel_delete_salesordernew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('delivery_number', models.CharField(max_length=50, unique=True)),
                ('delivery_date', models.DateField()),
                ('sales_order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('terms', models.CharField(blank=True, max_length=255)),
                ('due_date', models.DateField()),
                ('delivery_location', models.CharField(blank=True, max_length=255)),
                ('delivery_address', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.salesperson')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('delivery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.deliveryformmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
    ]
