# Generated by Django 4.2.16 on 2025-02-28 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_deliveryformmodel_deliveryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryformmodel',
            name='sales_order_number',
        ),
        migrations.AddField(
            model_name='deliveryformmodel',
            name='sales_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='accounts.salesordermodel'),
            preserve_default=False,
        ),
    ]
