# Generated by Django 4.2.16 on 2025-02-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_deliveryformmodel_sales_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='delivered_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
