# Generated by Django 4.2.16 on 2025-01-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_supplier_supplierpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierpurchase',
            name='supplier_number',
        ),
        migrations.AddField(
            model_name='supplierpurchase',
            name='add_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierpurchase',
            name='purchase_number',
            field=models.CharField(default='Unknown', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='supplierpurchase',
            name='purchase_person',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
