# Generated by Django 4.2.16 on 2025-02-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_deliveryitem_delivered_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
