# Generated by Django 4.2.16 on 2025-02-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_deliveryitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryformmodel',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
