# Generated by Django 4.2.16 on 2025-01-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_supplierpurchase_supplier_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('delivery_challan_number', models.CharField(max_length=50, unique=True)),
                ('customer_note', models.TextField(blank=True)),
            ],
        ),
    ]
