# Generated by Django 4.2.16 on 2025-01-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_product_invoiceorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceorder',
            name='product',
        ),
    ]
