# Generated by Django 4.2.16 on 2025-01-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_invoiceorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceorder',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.product'),
        ),
    ]
