# Generated by Django 4.2.16 on 2025-01-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_invoiceorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='contact_us',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='rate_us',
            field=models.CharField(blank=True, choices=[('great', '😊 Great'), ('okay', '😐 Okay'), ('bad', '😞 Bad')], default=1, max_length=5),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
