# Generated by Django 4.2.16 on 2025-03-19 08:57

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_customer_country_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
