# Generated by Django 4.2.16 on 2025-01-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_product_price_remove_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpurchase',
            name='product_name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
