# Generated by Django 4.2.16 on 2025-03-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_salesperson_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='display_name',
        ),
    ]
