# Generated by Django 4.2.16 on 2025-03-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_salesperson_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
