# Generated by Django 4.2.16 on 2025-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('liter', 'Liter'), ('meter', 'Meter'), ('box', 'Box'), ('dozen', 'Dozen')], max_length=50),
        ),
    ]
