# Generated by Django 4.2.16 on 2025-03-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_terms_quotationordermodel_remark_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='subject',
        ),
    ]
