# Generated by Django 4.2.16 on 2025-03-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_quotationordermodel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationordermodel',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
            preserve_default=False,
        ),
    ]
