# Generated by Django 4.2.16 on 2025-03-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_quotationordermodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='customer',
        ),
    ]
