# Generated by Django 4.2.16 on 2025-03-28 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_quotationordermodel_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationordermodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
    ]
