# Generated by Django 4.2.16 on 2025-03-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_quotationordermodel_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='customer',
        ),
        migrations.AddField(
            model_name='quotationordermodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
