# Generated by Django 4.2.16 on 2025-04-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_quotationordermodel_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('ifsc_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='quotationordermodel',
            name='address',
            field=models.TextField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
    ]
