# Generated by Django 4.2.16 on 2025-04-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_bankaccount_alter_quotationordermodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationordermodel',
            name='delivery_location',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
