# Generated by Django 4.2.16 on 2025-04-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_quotationordermodel_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='accounts.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationordermodel',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='accounts.bankaccount'),
        ),
    ]
