# Generated by Django 4.2.16 on 2025-04-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_bankaccount_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
