# Generated by Django 4.2.16 on 2025-04-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_quotationitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='remark',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
