# Generated by Django 4.2.16 on 2025-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_salesorder_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesordermodel',
            name='remark',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
