# Generated by Django 4.2.16 on 2025-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_salesordermodel_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
