# Generated by Django 4.2.16 on 2025-04-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_salesorderitem_cgst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderitem',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.quotationitem'),
        ),
    ]
