# Generated by Django 4.2.16 on 2025-04-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_salesorderitem_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesordermodel',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
