# Generated by Django 4.2.16 on 2025-04-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_product_cgst_product_sgst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CGST percentage (e.g. 9.00)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SGST percentage (e.g. 9.00)', max_digits=12),
        ),
    ]
