# Generated by Django 4.2.16 on 2025-04-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_product_cgst_alter_product_sgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SalesPerson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.salesperson'),
            preserve_default=False,
        ),
    ]
