# Generated by Django 4.2.16 on 2025-04-19 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_product_salesperson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SalesPerson',
            new_name='salesperson',
        ),
    ]
