# Generated by Django 4.2.16 on 2025-04-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_rename_salesperson_product_salesperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='email_id',
        ),
    ]
