# Generated by Django 4.2.16 on 2025-04-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_remove_quotationordermodel_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='salesperson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.salesperson'),
            preserve_default=False,
        ),
    ]
