# Generated by Django 4.2.16 on 2025-04-22 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_customer_salesperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesordermodel',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='salesordermodel',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='salesordermodel',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='salesordermodel',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='accounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='salesordermodel',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
    ]
