# Generated by Django 4.2.16 on 2025-04-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_remove_salesordermodel_contact_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderitem',
            name='quotation',
        ),
    ]
