# Generated by Django 4.2.16 on 2025-04-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_remove_salesorderitem_quotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesordermodel',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='salesordermodel',
            name='quotation_number',
        ),
    ]
