# Generated by Django 4.2.16 on 2025-04-29 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_rename_customer_name_salesordermodel_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesordermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
