# Generated by Django 4.2.16 on 2025-04-29 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_salesordermodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditionsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('terms_and_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.termsandconditions')),
            ],
        ),
    ]
