# Generated by Django 4.2.16 on 2025-04-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_termsandconditions_termsandconditionspoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationordermodel',
            name='termsandconditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termsandconditions', to='accounts.termsandconditions'),
        ),
    ]
