# Generated by Django 4.2.16 on 2025-04-30 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_quotationordermodel_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesordermodel',
            name='termsandconditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.termsandconditions'),
        ),
    ]
