# Generated by Django 4.2.16 on 2025-05-04 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_invoiceitem_invoicemodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='bank_account',
        ),
        migrations.AlterField(
            model_name='quotationordermodel',
            name='termsandconditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termsandconditionspoint', to='accounts.termsandconditionspoint'),
        ),
    ]
