# Generated by Django 4.2.16 on 2025-05-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_remove_quotationordermodel_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesordermodel',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='salesordermodel',
            name='terms',
        ),
    ]
