# Generated by Django 4.2.16 on 2025-05-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_remove_salesordermodel_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationordermodel',
            name='termsandconditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.termsandconditions'),
        ),
    ]
