# Generated by Django 4.2.16 on 2025-05-07 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_invoicemodel_is_receipted_receiptmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmodel',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.invoicemodel'),
        ),
    ]
