# Generated by Django 4.2.16 on 2025-05-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_receiptmodel_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_grand_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
