# Generated by Django 4.2.16 on 2025-05-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_invoicemodel_invoice_grand_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesordermodel',
            old_name='sales_order_id',
            new_name='sales_order_number',
        ),
    ]
