# Generated by Django 4.2.16 on 2025-05-13 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_alter_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='accounts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order_number', models.CharField(max_length=50, unique=True)),
                ('purchase_order_date', models.DateField()),
                ('contact_person_name', models.CharField(max_length=50)),
                ('contact_person_number', models.CharField(max_length=50)),
                ('quotation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
                ('terms_and_conditions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.termsandconditions')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.purchaseorder')),
            ],
        ),
        migrations.DeleteModel(
            name='SupplierPurchase',
        ),
        migrations.AddField(
            model_name='contractpoint',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='accounts.contractsection'),
        ),
    ]
