# Generated by Django 4.2.16 on 2025-05-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_contract_contractpoint_contractsection_purchaseorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
