# Generated by Django 4.2.16 on 2025-05-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_purchaseorder_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
