# Generated by Django 4.2.16 on 2025-05-15 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_purchaseorderitem_sub_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_receive_number', models.CharField(max_length=50, unique=True)),
                ('received_date', models.DateField()),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialReceiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('material_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.materialreceive')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.product')),
            ],
        ),
    ]
