# Generated by Django 4.2.16 on 2025-05-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_alter_purchaseorderitem_sub_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationordermodel',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contract'),
        ),
    ]
