# Generated by Django 4.2.16 on 2025-05-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_quotationordermodel_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='remark',
        ),
    ]
