# Generated by Django 4.2.16 on 2025-05-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_product_stock'),
        ('accounts', '0073_remove_supplier_supplier_display_name_and_more'),
    ]

    operations = [
    ]
