# Generated by Django 4.2.16 on 2025-05-16 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_merge_20250516_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationordermodel',
            old_name='address',
            new_name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='quotationordermodel',
            name='salesperson',
        ),
        migrations.AddField(
            model_name='quotationordermodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='quotationordermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
