# Generated by Django 4.2.16 on 2025-05-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_rename_address_quotationordermodel_delivery_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='salesperson',
        ),
    ]
