# Generated by Django 4.2.16 on 2025-05-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_alter_customer_address_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationordermodel',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
