# Generated by Django 4.2.16 on 2025-05-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_quotationordermodel_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
