# Generated by Django 4.2.16 on 2025-05-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_contract_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialreceiveitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
