# Generated by Django 4.2.16 on 2025-06-03 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_alter_materialreceiveitem_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('quotation', 'Quotation'), ('sales_order', 'Sales Order'), ('delivery', 'Delivery'), ('client', 'Client'), ('sales_person', 'Sales Person'), ('leads', 'Leads'), ('projects', 'Projects'), ('supplier', 'Supplier'), ('purchase', 'Purchase'), ('material_receive', 'Material Receive'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('stock', 'Stock'), ('expense', 'Expense'), ('reports', 'Reports'), ('returns', 'Sales Returns'), ('accounts', 'Accounts'), ('payments', 'Payments'), ('contracts', 'Contracts')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'module_name')},
            },
        ),
    ]
