# Generated by Django 4.2.16 on 2025-06-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
