# Generated by Django 4.2.16 on 2025-08-02 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_alter_modulepermission_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='SalesReturnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_return_number', models.CharField(max_length=50, unique=True)),
                ('return_date', models.DateField()),
                ('reason', models.TextField()),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('delivery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.deliveryitem')),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.salesreturnmodel')),
            ],
        ),
    ]
