# Generated by Django 4.2.16 on 2025-08-04 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_deliveryitem_returned_quantity_salesreturnmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnmodel',
            name='sales_order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.salesordermodel'),
            preserve_default=False,
        ),
    ]
