# Generated by Django 4.2.16 on 2025-08-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_salesreturnmodel_sales_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnmodel',
            name='termsandconditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.termsandconditions'),
        ),
    ]
