# Generated by Django 4.2.16 on 2025-08-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_salesreturnmodel_termsandconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module_name',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('sales_order', 'Sales Order'), ('delivery', 'Delivery'), ('client', 'Client'), ('sales_person', 'Sales Person'), ('setup', 'Setup'), ('leads', 'Leads'), ('project_management', 'Project Management'), ('supplier', 'Supplier'), ('purchase', 'Purchase'), ('material_receive', 'Material Receive'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('sales_return', 'Sales Return'), ('stock', 'Stock'), ('expense', 'Expense'), ('reports', 'Reports'), ('sales_returns', 'Sales Returns'), ('accounts', 'Accounts'), ('payments', 'Payments'), ('products', 'Products'), ('hr_section', 'HR Section')], max_length=50),
        ),
    ]
