# Generated by Django 4.2.16 on 2025-08-06 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_alter_modulepermission_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryformmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='deliveryformmodel',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='accounts.salesordermodel'),
        ),
        migrations.AlterField(
            model_name='deliveryformmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.salesordermodel'),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receiptmodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='receiptmodel',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.invoicemodel'),
        ),
        migrations.AlterField(
            model_name='receiptmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product'),
        ),
        migrations.AlterField(
            model_name='salesordermodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='salesordermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='delivery_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.deliveryitem'),
        ),
        migrations.AlterField(
            model_name='salesreturnmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='salesreturnmodel',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.salesordermodel'),
        ),
        migrations.AlterField(
            model_name='salesreturnmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
