# Generated by Django 4.2.16 on 2025-08-07 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_lead_status'),
        ('accounts', '0091_alter_deliveryformmodel_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationordermodel',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.product'),
        ),
        migrations.AlterField(
            model_name='quotationordermodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='quotationordermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
