# Generated by Django 4.2.16 on 2025-08-08 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_lead_status'),
        ('accounts', '0092_quotationordermodel_lead_alter_quotationitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationordermodel',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='leads.lead'),
        ),
    ]
