# Generated by Django 4.2.16 on 2025-08-08 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_lead_lead_status'),
        ('accounts', '0093_alter_quotationordermodel_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationordermodel',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotation', to='leads.lead'),
        ),
    ]
