# Generated by Django 4.2.16 on 2025-08-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_receiptmodel_cheque_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptmodel',
            name='termsandconditions',
        ),
        migrations.AddField(
            model_name='receiptmodel',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptmodel',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receiptmodel',
            name='recived_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
