# Generated by Django 4.2.16 on 2025-09-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_department_staffprofile_staffdocument_jobdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_logout_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
