# Generated by Django 4.2.16 on 2025-10-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_customuser_force_logout_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full day', 'Full Day'), ('part time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
