# Generated by Django 4.2.16 on 2025-10-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_jobdetail_job_type_staffprofile_staff_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/signatures/'),
        ),
    ]
