# Generated by Django 4.2.16 on 2025-11-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0102_jobdetail_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='assigned_staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salespersons', to='accounts.staffprofile'),
        ),
    ]
