# Generated by Django 4.2.16 on 2025-11-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_salesperson_assigned_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module_name',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('sales_order', 'Sales Order'), ('delivery', 'Delivery'), ('client', 'Client'), ('sales_person', 'Sales Person'), ('setup', 'Setup'), ('leads', 'Leads'), ('leads_management', 'Leads Management'), ('project_management', 'Project Management'), ('supplier', 'Supplier'), ('purchase', 'Purchase'), ('material_receive', 'Material Receive'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('reports', 'Reports'), ('sales_returns', 'Sales Returns'), ('accounts', 'Accounts'), ('products', 'Products'), ('hr_section', 'HR Section'), ('marketing', 'Marketing'), ('certificate', 'Certificate')], max_length=50),
        ),
    ]
