# Generated by Django 4.2.16 on 2025-11-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0104_alter_modulepermission_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'Probation'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
