# Generated by Django 4.2.16 on 2025-12-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_alter_modulepermission_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='job_type',
            field=models.CharField(blank=True, choices=[('full_day', 'Full Day'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=50, null=True),
        ),
    ]
