# Generated by Django 4.2.16 on 2025-12-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_customuser_emergency_contact_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmodel',
            name='cheque_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='receiptmodel',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
