# Generated by Django 4.2.16 on 2026-01-10 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_alter_receiptmodel_cheque_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.salesordermodel'),
        ),
    ]
