# Generated by Django 4.2.16 on 2026-01-14 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_alter_courseinstallment_options_coursepayment'),
        ('accounts', '0111_invoiceitem_cgst_invoiceitem_cgst_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='internship.course'),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intern_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='invoice_type',
            field=models.CharField(choices=[('client', 'Client'), ('intern', 'Intern')], default='client', max_length=20),
        ),
    ]
