# Generated by Django 4.2.16 on 2026-01-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_invoicemodel_course_invoicemodel_intern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoicemodel',
            name='intern_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
