# Generated by Django 4.2.16 on 2026-01-15 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_invoicemodel_course_name_invoicemodel_intern_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicemodel',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intern_invoices', to='accounts.staffprofile'),
        ),
    ]
