# Generated by Django 4.2.16 on 2026-01-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0114_alter_invoicemodel_intern'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
