# Generated by Django 4.2.16 on 2026-01-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_taxsettings_name'),
        ('accounts', '0115_invoicemodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.taxsettings'),
        ),
    ]
