# Generated by Django 4.2.16 on 2026-01-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_product_tax_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cgst',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sgst',
        ),
    ]
