# Generated by Django 4.2.16 on 2026-01-20 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_remove_product_cgst_remove_product_sgst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicemodel',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='invoicemodel',
            name='intern_name',
        ),
    ]
