# Generated by Django 4.2.16 on 2026-01-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_remove_invoicemodel_course_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicemodel',
            options={'ordering': ['-created_at']},
        ),
    ]
