# Generated by Django 4.2.16 on 2026-01-20 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0119_alter_invoicemodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmodel',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.invoicemodel'),
        ),
    ]
