# Generated by Django 4.2.16 on 2026-01-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_journalentry_type'),
        ('accounts', '0120_alter_receiptmodel_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmodel',
            name='tax_setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.taxsettings'),
        ),
    ]
