# Generated by Django 4.2.16 on 2026-01-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0121_receiptmodel_tax_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptmodel',
            name='tax_setting',
        ),
        migrations.AddField(
            model_name='receiptmodel',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
