# Generated by Django 4.2.16 on 2026-02-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_course_tax_settings'),
        ('accounts', '0122_remove_receiptmodel_tax_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='internship.course'),
        ),
        migrations.AddField(
            model_name='receiptmodel',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='intern_receipts', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='receiptmodel',
            name='receipt_type',
            field=models.CharField(choices=[('client', 'Client'), ('intern', 'Intern')], default='client', max_length=20),
        ),
    ]
