# Generated by Django 4.2.16 on 2026-02-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_receiptmodel_course_receiptmodel_intern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
