# Generated by Django 4.2.16 on 2026-02-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0124_customuser_gst_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gst_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
