# Generated by Django 4.2.16 on 2026-02-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0125_remove_customuser_gst_number_customer_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmodel',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
