# Generated by Django 4.2.16 on 2026-02-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0126_alter_receiptmodel_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmodel',
            name='tax_rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
