# Generated by Django 4.2.16 on 2026-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0128_alter_receiptmodel_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
