# Generated by Django 4.2.16 on 2026-02-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0130_product_code_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
