# Generated by Django 4.2.16 on 2026-02-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0133_delete_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module_name',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('finance', 'Finance'), ('crm', 'CRM'), ('hr', 'HR')], max_length=50),
        ),
    ]
