# Generated by Django 4.2.16 on 2026-03-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0135_alter_modulepermission_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='module_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('client', 'Client')], default='lead', max_length=10),
        ),
    ]
