# Generated by Django 4.2.16 on 2026-03-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0136_customer_module_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='module_type',
            field=models.CharField(blank=True, choices=[('lead', 'Lead'), ('client', 'Client')], max_length=10, null=True),
        ),
    ]
