# Generated by Django 4.2.16 on 2026-03-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0140_bankaccount_created_by_category_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_by',
        ),
    ]
