# Generated by Django 4.2.16 on 2026-03-09 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_lead_lead_category'),
        ('accounts', '0141_remove_bankaccount_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='customer',
            name='lead_contact',
            field=models.BooleanField(default=False),
        ),
    ]
