# Generated by Django 4.2.16 on 2026-03-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0142_customer_lead_customer_lead_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='lead_contact',
        ),
    ]
