# Generated by Django 4.2.16 on 2026-03-09 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0143_alter_modulepermission_module_name'),
        ('accounts', '0143_remove_customer_lead_contact'),
    ]

    operations = [
    ]
