# Generated by Django 4.2.16 on 2026-03-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0144_merge_20260309_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module_name',
            field=models.CharField(choices=[('quotation', 'Quotation'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('sales_returns', 'Sales Returns'), ('sales_reports', 'Sales Reports'), ('products', 'Products'), ('stock', 'Stock'), ('purchase_order', 'Purchase Order'), ('material_receive', 'Material Receive'), ('supplier', 'Supplier'), ('purchase_reports', 'Purchase Reports'), ('marketing_data', 'Marketing Data'), ('marketing_leads', 'Marketing Leads'), ('marketing_report', 'Marketing Report'), ('leads_management', 'Leads Management'), ('crm_reports', 'CRM Reports'), ('hr_enquiries', 'HR Enquiries'), ('hr_staff_management', 'HR Staff Management'), ('hr_attendance', 'HR Attendance'), ('hr_holidays', 'HR Holidays'), ('hr_leaves', 'HR Leaves'), ('hr_payroll', 'HR Payroll'), ('hr_salary_statements', 'HR Salary Statements'), ('task_all', 'All Tasks'), ('task_study_material', 'Study Material'), ('task_interns', 'Interns'), ('task_submissions', 'Task Submissions'), ('task_payments', 'Task Payments'), ('intern_all_task', 'Intern Tasks'), ('intern_study_materials', 'Intern Study Materials'), ('intern_payments', 'Intern Payments'), ('journal_entries', 'Journal Entries'), ('journal_voucher', 'Journal Voucher'), ('chart_of_accounts', 'Chart of Accounts'), ('tax_settings', 'Tax Settings'), ('finance_reports', 'Finance Reports'), ('transactions', 'Transactions'), ('project', 'Project'), ('project_timeline', 'Project Timeline'), ('project_reports', 'Project Reports'), ('certificate', 'Certificate'), ('home', 'Home'), ('setup', 'Set up'), ('sales_person', 'Sales Person'), ('hr_reports', 'HR Reports'), ('internship_reports', 'Internship Reports'), ('inventory_reports', 'Inventory Reports')], max_length=50),
        ),
    ]
