# Generated by Django 4.2.16 on 2026-03-17 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0146_alter_modulepermission_module_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptmodel',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='accounts.invoicemodel'),
        ),
    ]
