# Generated by Django 4.2.16 on 2026-03-17 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0147_alter_receiptmodel_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnmodel',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_returns', to='accounts.invoicemodel'),
        ),
    ]
