# Generated by Django 4.2.16 on 2026-03-18 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0148_salesreturnmodel_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturnitem',
            name='delivery_item',
        ),
        migrations.RemoveField(
            model_name='salesreturnmodel',
            name='sales_order',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.invoiceitem'),
        ),
    ]
