# Generated by Django 4.2.16 on 2026-03-18 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0149_remove_salesreturnitem_delivery_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturnitem',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.invoiceitem'),
        ),
    ]
