# Generated by Django 4.2.16 on 2026-03-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0150_alter_salesreturnitem_invoice_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturnitem',
            name='invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.invoiceitem'),
        ),
    ]
