# Generated by Django 6.0.6 on 2026-07-16 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0158_alter_modulepermission_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractpoint',
            name='section',
        ),
        migrations.CreateModel(
            name='ContractSubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='accounts.contractsection')),
            ],
        ),
        migrations.AddField(
            model_name='contractpoint',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='accounts.contractsubtitle'),
        ),
    ]
