# Generated by Django 4.2.16 on 2026-08-21 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0160_alter_modulepermission_module_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='accounts.jobdetail')),
            ],
        ),
        migrations.CreateModel(
            name='StaffDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('job_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='accounts.jobdetail')),
            ],
        ),
    ]
