# Generated by Django 4.2.16 on 2026-09-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0163_alter_modulepermission_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistration',
            name='converted_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_registrations', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='employeeregistration',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
    ]
