# Generated by Django 6.0.6 on 2026-09-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0164_employeeregistration_converted_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmodel',
            name='receipt_for',
            field=models.CharField(blank=True, choices=[('slot', 'Slot'), ('advance', 'Advance'), ('installment', 'Installment'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
