# Generated by Django 4.2.16 on 2025-12-04 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0106_alter_modulepermission_module_name'),
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedStaffCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.course')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assignedstaffcourse',
            constraint=models.UniqueConstraint(fields=('staff', 'course'), name='unique_staff_course'),
        ),
    ]
