# Generated by Django 4.2.16 on 2025-12-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_alter_receiptmodel_cheque_amount_and_more'),
        ('internship', '0005_course_created_at_course_number_of_installments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseinstallment',
            options={'ordering': ['created_at']},
        ),
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('upi', 'UPI')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='internship.courseinstallment')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to='accounts.staffprofile')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
