# Generated by Django 4.2.16 on 2026-01-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_taxsettings_name'),
        ('internship', '0006_alter_courseinstallment_options_coursepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tax_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.taxsettings'),
        ),
    ]
