# Generated by Django 4.2.16 on 2026-04-10 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0151_alter_modulepermission_module_name'),
        ('internship', '0007_course_tax_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='number_of_installments',
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_installments', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_plans', to='internship.course')),
            ],
            options={
                'ordering': ['total_installments'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_days', models.PositiveIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='internship.installmentplan')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to='accounts.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='accounts.department')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to='internship.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='internship.course')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='internship.coursefaculty')),
            ],
        ),
        migrations.AddIndex(
            model_name='installmentplan',
            index=models.Index(fields=['course'], name='internship__course__8cc6ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installmentplan',
            unique_together={('course', 'total_installments')},
        ),
        migrations.AlterUniqueTogether(
            name='installmentitem',
            unique_together={('plan', 'installment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('course', 'batch_number')},
        ),
    ]
