# Generated by Django 4.2.16 on 2026-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_batch_center_installmentplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepayment',
            name='installment',
        ),
        migrations.RemoveField(
            model_name='coursepayment',
            name='staff',
        ),
        migrations.AddConstraint(
            model_name='coursepayment',
            constraint=models.UniqueConstraint(fields=('student', 'installments'), name='unique_student_installment_payment'),
        ),
    ]
