# Generated by Django 4.2.16 on 2026-04-10 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_remove_course_number_of_installments_installmentplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_faculties', to='internship.faculty'),
        ),
    ]
