# Generated by Django 4.2.16 on 2026-04-16 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0151_alter_modulepermission_module_name'),
        ('internship', '0009_remove_coursepayment_installment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='country',
        ),
        migrations.RemoveField(
            model_name='center',
            name='state',
        ),
        migrations.AddField(
            model_name='batch',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='batches', to='internship.faculty'),
        ),
        migrations.AddField(
            model_name='center',
            name='country_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='center',
            name='state_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='faculties',
            field=models.ManyToManyField(blank=True, related_name='courses', to='internship.faculty'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coursefaculty',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_faculties', to='accounts.department'),
        ),
    ]
