# Generated by Django 5.2.7 on 2026-04-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_remove_center_country_remove_center_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='faculty',
        ),
    ]
