# Generated by Django 4.2.16 on 2026-04-17 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0151_alter_modulepermission_module_name'),
        ('internship', '0011_remove_batch_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.student'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tasks', through='internship.TaskAssignment', to='internship.student'),
        ),
        migrations.AlterField(
            model_name='taskassignment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile'),
        ),
    ]
