# Generated by Django 4.2.16 on 2026-04-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_taskassignment_student_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'student')},
        ),
    ]
