# Generated by Django 4.2.16 on 2026-04-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_remove_center_location_center_address_center_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
