# Generated by Django 4.2.16 on 2026-04-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0013_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
