# Generated by Django 4.2.16 on 2026-04-18 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0014_class_section_sectionday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='max_students',
        ),
    ]
