# Generated by Django 4.2.16 on 2026-04-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0015_remove_section_max_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='installments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_payments', to='internship.installmentitem'),
        ),
    ]
