# Generated by Django 4.2.16 on 2026-04-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0016_alter_coursepayment_installments'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coursepayment',
            name='unique_student_installment_payment',
        ),
    ]
