# Generated by Django 4.2.16 on 2026-04-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0017_remove_coursepayment_unique_student_installment_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymaterial',
            name='batch',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='batches',
            field=models.ManyToManyField(blank=True, related_name='study_materials', to='internship.batch'),
        ),
    ]
