# Generated by Django 4.2.16 on 2026-04-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0018_remove_studymaterial_batch_studymaterial_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='internship.batch'),
        ),
    ]
