# Generated by Django 4.2.16 on 2026-04-21 09:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0019_task_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('primary_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10–15 digits, optional +).', regex='^\\+?\\d{10,15}$')])),
                ('secondary_phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10–15 digits, optional +).', regex='^\\+?\\d{10,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('qualification', models.CharField(choices=[('sslc', 'SSLC'), ('plus_two', 'Plus Two'), ('ug', 'Undergraduate'), ('pg', 'Postgraduate')], max_length=20)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('where_did_you_find_us', models.CharField(blank=True, choices=[('google', 'Google'), ('social_media', 'Social Media'), ('friend', 'Friend'), ('other', 'Other')], max_length=20, null=True)),
                ('other_source', models.CharField(blank=True, max_length=255, null=True)),
                ('course_applied_for', models.CharField(max_length=255)),
                ('course_duration', models.PositiveIntegerField(help_text='Duration in months')),
                ('course_type', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10)),
                ('linkedin_profile_url', models.URLField(blank=True, null=True)),
                ('github_profile_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('academic_counselor', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('qualification', 'Qualification Document'), ('legal', 'Legal Document')], max_length=20, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='internship.internshipapplication')),
            ],
        ),
    ]
