# Generated by Django 4.2.16 on 2026-05-02 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0021_test_testsection_testquestion_questionoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='internship.batch'),
        ),
    ]
