# Generated by Django 4.2.16 on 2026-05-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0023_testattempt_testanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
