# Generated by Django 4.2.16 on 2026-05-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0155_alter_modulepermission_module_name'),
        ('internship', '0024_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='faculties', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_faculties', to='accounts.department'),
        ),
        migrations.DeleteModel(
            name='CourseFaculty',
        ),
    ]
