# Generated by Django 4.2.16 on 2026-05-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0026_reporttemplate_templatesection_templatefield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='overall_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
