# Generated by Django 5.2.14 on 2026-06-11 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0027_testattempt_overall_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInstallmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_days', models.PositiveIntegerField()),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_installment_items', to='internship.studentcourseenrollment')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('enrollment', 'installment_number')},
            },
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='student_installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_payments_new', to='internship.studentinstallmentitem'),
        ),
    ]
