# Generated by Django 4.2 on 2026-06-11 11:29
from django.db import migrations

def populate_student_installments(apps, schema_editor):
    StudentCourseEnrollment = apps.get_model('internship', 'StudentCourseEnrollment')
    StudentInstallmentItem = apps.get_model('internship', 'StudentInstallmentItem')
    CoursePayment = apps.get_model('internship', 'CoursePayment')
    InstallmentItem = apps.get_model('internship', 'InstallmentItem')

    for enrollment in StudentCourseEnrollment.objects.filter(installment_plan__isnull=False):
        plan = enrollment.installment_plan
        global_items = InstallmentItem.objects.filter(plan=plan)
        for item in global_items:
            StudentInstallmentItem.objects.get_or_create(
                enrollment=enrollment,
                installment_number=item.installment_number,
                defaults={
                    'amount': item.amount,
                    'due_days': item.due_days
                }
            )

    for payment in CoursePayment.objects.filter(installments__isnull=False):
        global_item = payment.installments
        enrollment = StudentCourseEnrollment.objects.filter(
            student=payment.student,
            course=global_item.plan.course
        ).first()

        if enrollment:
            student_item = StudentInstallmentItem.objects.filter(
                enrollment=enrollment,
                installment_number=global_item.installment_number
            ).first()

            if student_item:
                payment.student_installment = student_item
                payment.save(update_fields=['student_installment'])

def reverse_populate_student_installments(apps, schema_editor):
    CoursePayment = apps.get_model('internship', 'CoursePayment')
    StudentInstallmentItem = apps.get_model('internship', 'StudentInstallmentItem')
    
    CoursePayment.objects.all().update(student_installment=None)
    StudentInstallmentItem.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0028_studentinstallmentitem_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_student_installments,
            reverse_populate_student_installments
        ),
    ]