# Generated by Django 5.2.14 on 2026-06-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0029_auto_20260611_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepayment',
            name='installments',
        ),
    ]
