# Generated by Django 5.2.14 on 2026-06-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0030_remove_coursepayment_installments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepayment',
            old_name='student_installment',
            new_name='installments',
        ),
    ]
