# Generated by Django 5.2.14 on 2026-06-11 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0031_rename_student_installment_coursepayment_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepayment',
            name='installments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_payments', to='internship.studentinstallmentitem'),
        ),
    ]
