# Generated by Django 4.2.16 on 2026-06-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0032_alter_coursepayment_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepayment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='internship.studentcourseenrollment'),
        ),
        migrations.AddField(
            model_name='coursepayment',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Advance'), ('installment', 'Installment')], default='installment', max_length=20),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('upi', 'UPI')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coursepayment',
            name='payment_date',
            field=models.DateField(),
        ),
    ]
