# Generated by Django 4.2.16 on 2026-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0033_coursepayment_enrollment_coursepayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='custom_installments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='payment_plan_type',
            field=models.CharField(choices=[('default_installment', 'Default Installment'), ('custom_installment', 'Custom Installment')], default='default_installment', max_length=30),
        ),
    ]
