# Generated by Django 6.0.6 on 2026-07-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0034_studentcourseenrollment_custom_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='discount_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
