# Generated by Django 4.2.16 on 2026-07-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0035_studentcourseenrollment_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='form_type',
            field=models.CharField(choices=[('internship_form', 'Internship Form'), ('free_course_form', 'Free Course Form')], default='internship_form', max_length=20),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='course_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('recorded', 'Recorded')], max_length=10),
        ),
    ]
