# Generated by Django 6.0.6 on 2026-08-04 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0036_internshipapplication_form_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='converted_students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_applications', to='internship.student'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='is_converted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='slot_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='slot_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='slot_payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('upi', 'UPI')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='slot_transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='internship.internshipapplication'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='course_applied_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internship_applications', to='internship.course'),
        ),
    ]
