# Generated by Django 4.2.16 on 2026-08-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0160_alter_modulepermission_module_name'),
        ('internship', '0037_internshipapplication_converted_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='councellor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_applications', to='accounts.salesperson'),
        ),
    ]
