# Generated by Django 4.2.16 on 2026-08-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0038_internshipapplication_councellor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='course_applied_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
