# Generated by Django 4.2.16 on 2026-08-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0039_alter_internshipapplication_course_applied_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internship_applications', to='internship.course'),
        ),
    ]
