# Generated by Django 4.2.16 on 2026-09-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0040_internshipapplication_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slot_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
