# Generated by Django 4.2.16 on 2026-09-14 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0165_receiptmodel_receipt_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internship', '0041_student_slot_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorHRSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of conversion period')),
                ('end_date', models.DateField(help_text='End date of conversion period')),
                ('period_label', models.CharField(blank=True, help_text="e.g. 'April 2026' or 'Q1 2026'", max_length=100, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted to HR'), ('approved', 'Approved by HR'), ('rejected', 'Rejected by HR')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_submissions', to='accounts.salesperson')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_counsellor_hr_batches', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_counsellor_hr_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('counsellor', 'start_date', 'end_date')},
            },
        ),
    ]
