# Generated by Django 4.2.16 on 2026-09-16 05:15

from django.db import migrations, models


def backfill_course_fee(apps, schema_editor):
    StudentCourseEnrollment = apps.get_model('internship', 'StudentCourseEnrollment')
    for enrollment in StudentCourseEnrollment.objects.filter(
        course__isnull=False,
        course_fee__isnull=True
    ).select_related('course'):
        if enrollment.course and getattr(enrollment.course, 'total_fee', None) is not None:
            enrollment.course_fee = enrollment.course.total_fee
            enrollment.save(update_fields=['course_fee'])


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0042_counsellorhrsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='course_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of the course fee agreed upon at enrollment', max_digits=10, null=True),
        ),
        migrations.RunPython(backfill_course_fee, migrations.RunPython.noop),
    ]

