# Generated by Django 4.2.16 on 2026-02-10 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0128_alter_receiptmodel_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('is_locked', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('month',)},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('working_days', models.PositiveSmallIntegerField()),
                ('paid_leave_used', models.PositiveSmallIntegerField()),
                ('unpaid_leave_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Paid')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('working_days', models.PositiveSmallIntegerField()),
                ('full_days', models.PositiveSmallIntegerField()),
                ('half_days', models.PositiveSmallIntegerField()),
                ('leave_days', models.PositiveSmallIntegerField()),
                ('absent_days', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile')),
            ],
            options={
                'unique_together': {('staff', 'month')},
            },
        ),
    ]
