# Generated by Django 4.2.16 on 2026-02-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('GENERATED', 'Generated'), ('LOCKED', 'Locked')], default='OPEN', max_length=10),
        ),
    ]
