# Generated by Django 4.2.16 on 2026-02-12 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0128_alter_receiptmodel_tax_rate'),
        ('payroll', '0002_payrollperiod_generated_at_payrollperiod_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='payroll.payrollperiod'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='payroll.payrollperiod'),
        ),
        migrations.AlterField(
            model_name='attendancesummary',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='accounts.staffprofile'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='accounts.staffprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('staff', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('staff', 'period')},
        ),
    ]
