# Generated by Django 4.2.16 on 2026-02-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_attendancesummary_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollperiod',
            name='is_locked',
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('generated', 'Generated'), ('locked', 'Locked')], default='open', max_length=10),
        ),
    ]
