# Generated by Django 4.2.16 on 2026-02-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_payrollperiod_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollperiod',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Paid', 'Paid')], default='Draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='month',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
