# Generated by Django 4.2.16 on 2026-08-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_payrollearning_payrolldeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='total_working_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
