# Generated by Django 4.2.16 on 2025-09-23 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0100_customuser_force_logout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_working_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('leave', 'Leave'), ('half_day', 'Half Day'), ('full_day', 'Full Day')], default='leave', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendance', to='accounts.staffprofile')),
            ],
            options={
                'unique_together': {('staff', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('session1', 'Session 1'), ('session2', 'Session 2'), ('session3', 'Session 3')], max_length=10)),
                ('status', models.CharField(choices=[('leave', 'Leave'), ('late', 'Late'), ('present', 'Present')], default='leave', max_length=10)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('session_start', models.TimeField()),
                ('session_end', models.TimeField()),
                ('daily_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.dailyattendance')),
            ],
        ),
    ]
