# Generated by Django 4.2.16 on 2025-09-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='session_end',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='session_start',
        ),
    ]
