# Generated by Django 4.2.16 on 2026-02-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendancesession_session_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='status',
            field=models.CharField(choices=[('absent', 'Absent'), ('leave', 'Approved Leave'), ('half_day', 'Half Day'), ('full_day', 'Full Day')], default='absent', max_length=10),
        ),
    ]
